
services:

  db-users:
    image: mysql:8.0
    container_name: db-users
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: pp_users
      MYSQL_USER: TestUser
      MYSQL_PASSWORD: 28_08_2003
    ports:
      - "3306:3306"
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - db-users
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-users:3306/pp_users
      SPRING_DATASOURCE_USERNAME: TestUser
      SPRING_DATASOURCE_PASSWORD: 28_08_2003
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: